cabal-version:      3.0
name:               student-apps
version:            0.1.0.0
build-type:         Simple

common common-settings
  build-depends:      base >=4.14 && <5
  default-language:   GHC2021

executable hello
  import:             common-settings
  main-is:            Main.hs
  hs-source-dirs:     app/hello

executable goodbye
  import:             common-settings
  main-is:            Main.hs
  hs-source-dirs:     app/goodbye
